version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    env_file:
      - ./.env
  api:
    build: .
    ports:
      - ${API_PORT}:5000
    env_file:
      - ./.env
    command: "go run main.go"
    depends_on:
      - db
    volumes:
      - .:/go/src/API
