version: '3.1'

services:
  db:
    build: ./init_db/
    ports:
      - ${DB_PORT}:5432
    env_file:
      - ./.env
  api:
      build: .
      ports:
        - ${API_PORT}:5000
      env_file:
        - ./.env
      command: "go run main.go"
      depends_on:
        - db
      volumes:
        - .:/go/src/API
